name: Push File
on:
  release:
    types: [published]
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Construct Release URL
      id: construct_release_url
      run: |
        # Get the release tag name
        RELEASE_TAG="${{ github.event.release.tag_name }}"

        # Construct the release URL
        RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/${RELEASE_TAG}"

        # Set the release URL as an environment variable
        echo "RELEASE_URL=$RELEASE_URL" >> $GITHUB_ENV

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.test_token }}
        RELEASE_URL: ${{ env.RELEASE_URL }}
      with:
        source_file: 'utilities.py'
        destination_repo: 'nfrawley/test'
        destination_folder: '/'
        user_email: 'noah.frawley@proton.me'
        user_name: 'nfrawley'
        commit_message: 'copy new utilities.py version ${{ github.event.release.tag_name }} ${{ env.RELEASE_URL }}'
