name: Push File
on:
  release:
    types: [published]
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get commit URL from release
      id: get_commit_url
      run: |
        # Get the tag name and target_commitish (which can be a commit SHA or branch name)
        RELEASE_TAG="${{ github.event.release.tag_name }}"
        TARGET_COMMITISH="${{ github.event.release.target_commitish }}"

        echo "Release tag: $RELEASE_TAG"
        echo "Target commitish (commit hash or branch): $TARGET_COMMITISH"

        # If target_commitish is a branch name, we need to get the latest commit hash for that branch
        if [[ "$TARGET_COMMITISH" == *"/"* ]]; then
          COMMIT_SHA=$(git rev-parse "$TARGET_COMMITISH")
        else
          COMMIT_SHA="$TARGET_COMMITISH"
        fi

        # Build the commit URL
        COMMIT_URL="https://github.com/${{ github.repository }}/commit/${COMMIT_SHA}"

        echo "COMMIT_URL=$COMMIT_URL" >> $GITHUB_ENV

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.test_token }}
        COMMIT_URL: ${{ env.COMMIT_URL }}
      with:
        source_file: 'utilities.py'
        destination_repo: 'nfrawley/test'
        destination_folder: '/'
        user_email: 'noah.frawley@proton.me'
        user_name: 'nfrawley'
        commit_message: 'copy new utilities.py version ${{ github.event.release.tag_name }} ${{ env.COMMIT_URL }}'
