name: Push utilities file to required repos
on:
  release:
    types: [published]
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Construct Release URL
      id: construct_release_url
      run: |
        RELEASE_TAG="${{ github.event.release.tag_name }}"
        RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/${RELEASE_TAG}"
        echo "RELEASE_URL=$RELEASE_URL" >> $GITHUB_ENV

    - name: Read repositories from file and push file
      run: |
        REPO_LIST=".github/workflows/repos.txt"

        while IFS= read -r REPO; do
          if [ -n "$REPO" ]; then  # Ensure the line is not empty
            echo "Pushing to repository: $REPO"

            git clone --depth 1 https://github.com/${REPO}.git repo_temp
            cd repo_temp
            git config user.email "noah.frawley@proton.me"
            git config user.name "nfrawley"
            cp "../utilities.py" .
            git add utilities.py
            git commit -m "copy new utilities.py version ${{ github.event.release.tag_name }} ${{ env.RELEASE_URL }}"
            git push origin main
            cd ..
            rm -rf repo_temp
          fi
        done < "$REPO_LIST"
