name: Push File
on:
  release:
    types: [published]
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get commit URL from release
      id: get_commit_url
      run: |
        # Fetch the commit associated with the release tag using the GitHub API
        RELEASE_TAG="${{ github.event.release.tag_name }}"
        API_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/${RELEASE_TAG}"
        COMMIT_URL=$(curl -s $API_URL | jq -r .target_commitish)
        COMMIT_SHA=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${COMMIT_URL}" | jq -r .sha)
        COMMIT_URL="https://github.com/${{ github.repository }}/commit/${COMMIT_SHA}"
        echo "COMMIT_URL=$COMMIT_URL" >> $GITHUB_ENV

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.test_token }}
        COMMIT_URL: ${{ env.COMMIT_URL }}
      with:
        source_file: 'utilities.py'
        destination_repo: 'nfrawley/test'
        destination_folder: '/'
        user_email: 'noah.frawley@proton.me'
        user_name: 'nfrawley'
        commit_message: 'copy new utilities.py version ${{ github.event.release.tag_name }} ${{ env.COMMIT_URL }}'
