name: Push File to Multiple Repos
on:
  push:
    paths:
      - 'utilities.py'  # Trigger the workflow only when utilities.py changes

jobs:
  sync-utilities:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 1
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Clone Repository 2
        run: |
          git clone https://github.com/nfrawley/test.git
          cd test
          git checkout main  # Adjust if you're using a different branch

      - name: Copy utilities.py to Repository 2
        run: |
          cp ../utilities.py ./utilities.py

      - name: Commit and Push changes to Repository 2
        run: |
          cd test
          git add utilities.py
          git commit -m "Sync utilities.py from Repository 1"
          git push origin main  # Adjust branch name if necessary
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}

