name: Push File
on:
  workflow_dispatch:
    inputs:
      destination_repo:
        description: 'Repository to push the file to'
        required: true
        default: 'nfrawley/test'
      source_file:
        description: 'Source file to push'
        required: true
        default: 'utilities.py'
      commit_message:
        description: 'Commit message for the push'
        required: true
        default: 'AUTOMATED - copy new utilities.py version'
  repository_dispatch:
    types: [trigger-push-file]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Construct Release URL
      id: construct_release_url
      run: |
        # Get the release tag name (if applicable)
        RELEASE_TAG="${{ github.event.release.tag_name }}"
        # Construct the release URL
        RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/${RELEASE_TAG}"
        # Set the release URL as an environment variable
        echo "RELEASE_URL=$RELEASE_URL" >> $GITHUB_ENV

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.test_token }}
        RELEASE_URL: ${{ env.RELEASE_URL }}
      with:
        source_file: ${{ github.event.client_payload.source_file }}
        destination_repo: ${{ github.event.client_payload.destination_repo }}
        destination_folder: '/'
        user_email: 'noah.frawley@proton.me'
        user_name: 'nfrawley'
        commit_message: ${{ github.event.client_payload.commit_message }}
