name: Push File to raspi_streambot

on:
  release:
    types: [published]

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger the workflow in the other repository
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.TEST_TOKEN }}
        repository: 'nfrawley/py-utilities'
        event-type: 'trigger-push-file'
        client-payload: |
          {
            "destination_repo": "nfrawley/raspi_streambot",
            "source_file": "utilities.py",
            "commit_message": "AUTOMATED - new utilities.py version ${{ github.event.release.tag_name }} https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}"
          }
